import type { Metadata } from "next";
import "@/app/globals.css";
import localFont from "next/font/local";
import { MouseProvider } from "@/context/context";
import NavBar from "@/components/client/NavBar"


const lemonMilk = localFont({
  src: [
    { path: "../../public/fonts/LEMONMILK-Light.woff2",        weight: "300", style: "normal" },
    { path: "../../public/fonts/LEMONMILK-LightItalic.woff2",  weight: "300", style: "italic" },
    { path: "../../public/fonts/LEMONMILK-Medium.woff2",       weight: "500", style: "normal" },
    { path: "../../public/fonts/LEMONMILK-MediumItalic.woff2", weight: "500", style: "italic" },
    { path: "../../public/fonts/LEMONMILK-Bold.woff2",         weight: "700", style: "normal" },
    { path: "../../public/fonts/LEMONMILK-BoldItalic.woff2",   weight: "700", style: "italic" },
  ],
  display: "swap",
  preload: true,
  variable: "--font-lemonmilk",
  fallback: ["system-ui","-apple-system","Segoe UI","Roboto","Helvetica","Arial","sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${lemonMilk.variable} antialiased`}>
    
        <MouseProvider>
              <NavBar />
        {children}
          </MouseProvider>
   
      </body>
   
    </html>
  );
}
